spring:
  application:
    name: ms-administradores

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/db_administradores}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  sql:
    init:
      mode: always

  profiles:
    active: dev

server:
  port: 8081

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  packages-to-scan: notaria.jenny.ms_administradores